export const userManagementSeed = {
  STUDENT: [
    {
      id: 'student-1',
      firstName: 'أحمد',
      lastName: 'حسن',
      email: 'ahmed.hassan@example.com',
      phone: '0501234567',
      roles: ['STUDENT'],
      parentName: 'محمد حسن',
      parentLinked: true,
      isActive: true,
      joinedAt: '2024-01-15',
      avatarColor: 'from-violet-500 to-fuchsia-500',
    },
    {
      id: 'student-2',
      firstName: 'سارة',
      lastName: 'أحمد',
      email: 'sarah.ahmed@example.com',
      phone: '0507654321',
      roles: ['STUDENT'],
      parentName: 'فاطمة علي',
      parentLinked: true,
      isActive: true,
      joinedAt: '2024-02-20',
      avatarColor: 'from-purple-500 to-pink-500',
    },
    {
      id: 'student-3',
      firstName: 'عمر',
      lastName: 'خليل',
      email: 'omar.khalil@example.com',
      phone: '0567891234',
      roles: ['STUDENT'],
      parentName: '',
      parentLinked: false,
      isActive: true,
      joinedAt: '2024-04-05',
      avatarColor: 'from-violet-500 to-pink-500',
    },
    {
      id: 'student-4',
      firstName: 'عائشة',
      lastName: 'كريم',
      email: 'aisha.karim@example.com',
      phone: '0551239876',
      roles: ['STUDENT'],
      parentName: 'كريم أحمد',
      parentLinked: true,
      isActive: false,
      joinedAt: '2024-03-20',
      avatarColor: 'from-fuchsia-500 to-pink-500',
    },
  ],
  TEACHER: [
    {
      id: 'teacher-1',
      firstName: 'ليلى',
      lastName: 'محمود',
      email: 'layla.mahmoud@example.com',
      phone: '0591002001',
      roles: ['TEACHER'],
      parentName: '',
      parentLinked: false,
      isActive: true,
      joinedAt: '2023-09-02',
      avatarColor: 'from-sky-500 to-cyan-500',
    },
    {
      id: 'teacher-2',
      firstName: 'يوسف',
      lastName: 'سليم',
      email: 'youssef.salim@example.com',
      phone: '0591002002',
      roles: ['TEACHER'],
      parentName: '',
      parentLinked: false,
      isActive: true,
      joinedAt: '2023-10-11',
      avatarColor: 'from-cyan-500 to-blue-500',
    },
  ],
  PARENT: [
    {
      id: 'parent-1',
      firstName: 'محمد',
      lastName: 'حسن',
      email: 'mohammad.hassan@example.com',
      phone: '0587003001',
      roles: ['PARENT'],
      parentName: 'أحمد حسن',
      parentLinked: true,
      isActive: true,
      joinedAt: '2024-01-10',
      avatarColor: 'from-emerald-500 to-teal-500',
    },
    {
      id: 'parent-2',
      firstName: 'فاطمة',
      lastName: 'علي',
      email: 'fatima.ali@example.com',
      phone: '0587003002',
      roles: ['PARENT'],
      parentName: 'سارة أحمد',
      parentLinked: true,
      isActive: true,
      joinedAt: '2024-02-17',
      avatarColor: 'from-teal-500 to-emerald-500',
    },
  ],
};
