export const studentsData = [
  {
    id: 1,
    name: 'أحمد حسن',
    email: 'ahmed.hassan@example.com',
    phone: '0501234567',
    parentLinked: true,
    parentName: 'محمد حسن',
    status: 'active',
    date: '2024-01-15',
    avatar: 'أح',
    avatarColor: 'bg-purple-600',
  },
  {
    id: 2,
    name: 'سارة أحمد',
    email: 'sarah.ahmed@example.com',
    phone: '0507654321',
    parentLinked: true,
    parentName: 'فاطمة علي',
    status: 'active',
    date: '2024-02-20',
    avatar: 'سأ',
    avatarColor: 'bg-fuchsia-600',
  },
  {
    id: 3,
    name: 'عمر خليل',
    email: 'omar.khalil@example.com',
    phone: '0567891234',
    parentLinked: false,
    status: 'active',
    date: '2024-04-05',
    avatar: 'عخ',
    avatarColor: 'bg-violet-600',
  },
  {
    id: 4,
    name: 'عائشة كريم',
    email: 'aisha.karim@example.com',
    phone: '0551239876',
    parentLinked: true,
    parentName: 'كريم أحمد',
    status: 'inactive',
    date: '2024-03-20',
    avatar: 'عك',
    avatarColor: 'bg-purple-500',
  },
];